name: Build & Deploy
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt install zip

      - name: Checkout
        uses: actions/checkout@v2

      - name: Package ZetaBot
        run: ./build

  upload:
    name: Artifact
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        run: source ./version.sh

      - name: Upload as artifact
        uses: actions/upload-artifact@v2
        with:
          name: "zetabot_v${VERSION}.pk3"
          path: "Built/zetabot_v${VERSION}.pk3"

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        run: source ./version.sh

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: v$VERSION
          draft: true
          bodyFile: changelog/latest.md
          artifacts: "zetabot_v${VERSION}.pk3"
          prerelease: contains(github.ref, '-rc')
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive release log
        run: |
          cp changelog/latest.md changelog/archived/$VERSION.md

      - name: Commit archived log
        uses: EndBug/add-and-commit@v7.2.0
        with:
          add: changelog/archived/${VERSION}.md
          push: true
          message: "(CI) Archived changelog for v$VERSION"
